### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by KiAlexander** [chenjiandongx/51job#10]
Traceback (most recent call last):
  File "job_spider.py", line 338, in <module>
    spider.run()
  File "job_spider.py", line 329, in run
    self.job_spider()
  File "job_spider.py", line 90, in job_spider
    bs = BeautifulSoup(html, "lxml").find("div", class_="dw_table").find_all("div", class_="el")
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by flowers-baby** [comment]
你好，请问你这个问题解决了吗，怎么解决的呀
