### ISSUE TITLE
我把需要的程序也启动了但没有出现预期的那样

### ISSUE THREAD

**Issue by chromiea** [chenjiandongx/51job#13]
2019-09-23 01:04:32,404 - 爬取第 748 条岗位详情
爬完之后 就一直停滞在这了，只出现post_require_new.txt不太懂哪里出了出了差错
中间有一段儿是:
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "C:/Users/Administrator/Job/job_spider.py", line 106, in post_require
    html = resp.content.decode("gbk")
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 1060: illegal multibyte sequence
2019-09-22T17:03:11Z <Greenlet at 0x178d629c158: <bound method JobSpider.post_require of <__main__.JobSpider object at 0x00000178D6288C88>>> failed with UnicodeDecodeError

您能帮忙解惑吗？

**Comment by yingning** [comment]
请问您解决了这个问题了吗？ @chromiea
